spring:
  application:
    name: replication_core
  main:
    allow-circular-references: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/replication_core_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: abayu_management
    password: abayu_management
    virtual-host: replication_core_rabbit


server:
  port: 8081
