spring:
  application:
    name: replication_core
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/replication_core_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
